samples:
    ERR771001_1: "data/ERR771001_1"

run_settings:
    local_run: "false"
    cluster_config: "config/cluster.yml"
    scheduler: "sbatch"

pipeline:
    debug: 1 # Debugging message, set to 0 to turn off 
    adapter_fasta: "data/configs/TruSeq3-SE.fa" # Adapter file for Trimmomatic
    seed_mismatches: 2 # Max number of seed mismatches allowed for Trimmomatic
    palindrome_clip_thresh: 30 # palindromeClipThreshold parameter for Trimmomatic
    simple_clip_thresh: 10 # simpleClipThreshold parameter for Trimmomatic
    min_adapter_length: 2 # Minimum length of a sequence that can be considered an adapter for Trimmomatic
    min_quality: 3 # Minimum quality for leading and trailing bases, otherwise get trimmed, for Trimmomatic
    trim_min_length: 36 # Minimum length of reads to be kept after trimming, shorter reads are discarded, for Trimmomatic
    vsearch_filter_maxee: 20 # Discards sequences with more than specified number of errors, for vsearch
    vsearch_filter_minlen: 75 # Discards sequences with less than specified number of bases, for vsearch
    frag_train_file: "illumina_10" # File name that contains model parameters for FragGeneScan
    delete_intermediates: 0 # Whether to keep intermediate results or delete them to save space (0 = keep, 1 = delete) 

snakemake:
    threads_small: 4
    mem_small: 20000
    threads_big: 15
    mem_big: 75000
