samples:
    ERR771001_1: "data/ERR771001_1"
    #ERR771001_2: "data/ERR771001_2"

run_settings:
    local_run: "false"
    cluster_config: "config/cluster.yml"
    scheduler: "sbatch"

pipeline:
    threads: 10
    debug: 1
    paired_ends: 0
    adapter_fasta: "data/configs/TruSeq3-PE.fa"
    seed_mismatches: 2
    palindrome_clip_thresh: 30
    simple_clip_thresh: 10
    min_adapter_length: 2
    keep_both_reads: "keepBothReads"
    min_quality: 3
    trim_min_length: 36
    pear_min_length: 1
    pear_max_assembly: 1000
    pear_min_assembly: 2
    vsearch_filter_maxee: 20
    vsearch_filter_minlen: 75
    frag_train_file: "illumina_10"
    delete_intermediates: 0

